name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      DEPLOY_DIR: C:\hospital-frontend

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build frontend
      - name: Build frontend
        run: npm run build

      # 5. Deploy to local folder
      - name: Deploy frontend
        run: |
          if not exist "${{ env.DEPLOY_DIR }}" mkdir "${{ env.DEPLOY_DIR }}"
          powershell -Command "Remove-Item -Recurse -Force '${{ env.DEPLOY_DIR }}\*'"
          xcopy /E /I /Y dist\* "${{ env.DEPLOY_DIR }}\"
